#!/bin/bash
#Author: Nicolas Nunez
#Comments: Install more properly...

echo "Install more properly..."
REDIS_USER=${1}
REDIS_CUSTOM_PORT=${2}
REDIS_CONF_DIR_PATH=${3}
REDIS_WORKING_DIR_PATH=${4}
REDIS_LOG_DIR_PATH=${5}
REDIS_PID_DIR_PATH=${6}

echo "Redis User: ${REDIS_USER}"
echo "Redis Port: ${REDIS_CUSTOM_PORT}"
echo "Redis Config Dir: ${REDIS_CONF_DIR_PATH}"
echo "Redis Working Dir: ${REDIS_WORKING_DIR_PATH}"
echo "Redis Log Dir: ${REDIS_LOG_DIR_PATH}"
echo "Redis PID Dir: ${REDIS_PID_DIR_PATH}"


REDIS_CUSTOM_PREFIX=${REDIS_USER}_${REDIS_CUSTOM_PORT}

echo "Prefix: ${REDIS_CUSTOM_PREFIX}"

REDIS_CONF_FILE_FULL_PATH=${REDIS_CONF_DIR_PATH}/${REDIS_CUSTOM_PREFIX}.conf
REDIS_LOG_FILE_FULL_PATH=${REDIS_LOG_DIR_PATH}/${REDIS_CUSTOM_PREFIX}.log
REDIS_DATA_DIR_PATH=${REDIS_WORKING_DIR_PATH}/${REDIS_CUSTOM_PREFIX}
REDIS_PID_FILE_FULL_PATH=${REDIS_PID_DIR_PATH}/${REDIS_CUSTOM_PREFIX}.pid

REDIS_PORT_PLACEHOLDER="REDIS_PORT_PLACEHOLDER"
REDIS_WORKING_DIR_PATH_PLACEHOLDER="REDIS_WORKING_DIR_PATH_PLACEHOLDER"
REDIS_CONF_FILE_PATH_PLACEHOLDER="REDIS_CONF_FILE_PATH_PLACEHOLDER"
REDIS_USER_PLACEHOLDER="REDIS_USER_PLACEHOLDER"
REDIS_USER_GROUP_PLACEHOLDER="REDIS_USER_GROUP_PLACEHOLDER"
REDIS_PID_FILE_FULL_PATH_PLACEHOLDER="REDIS_PID_FILE_FULL_PATH_PLACEHOLDER"
REDIS_LOG_FILE_FULL_PATH_PLACEHOLDER="REDIS_LOG_FILE_FULL_PATH_PLACEHOLDER"



#Configuration
sudo mkdir ${REDIS_CONF_DIR_PATH}
sudo chown -R ${REDIS_USER}:${REDIS_USER} ${REDIS_CONF_DIR_PATH}
#redis configuration file...
sudo cp ${HOME}/redis.conf ${REDIS_CONF_FILE_FULL_PATH}
sudo sed -i "s|${REDIS_PORT_PLACEHOLDER}|${REDIS_CUSTOM_PORT}|g" ${REDIS_CONF_FILE_FULL_PATH}
sudo sed -i "s|${REDIS_PID_FILE_FULL_PATH_PLACEHOLDER}|${REDIS_PID_FILE_FULL_PATH}|g" ${REDIS_CONF_FILE_FULL_PATH}
sudo sed -i "s|${REDIS_LOG_FILE_FULL_PATH_PLACEHOLDER}|${REDIS_LOG_FILE_FULL_PATH}|g" ${REDIS_CONF_FILE_FULL_PATH}
sudo sed -i "s|${REDIS_WORKING_DIR_PATH_PLACEHOLDER}|${REDIS_WORKING_DIR_PATH}|g" ${REDIS_CONF_FILE_FULL_PATH}

#Logs
sudo mkdir -p ${REDIS_LOG_DIR_PATH}
sudo touch ${REDIS_LOG_FILE_FULL_PATH}
sudo chown -R $REDIS_USER:$REDIS_USER ${REDIS_LOG_FILE_FULL_PATH}

#Data and Working Directory for this Redis instance
sudo mkdir -p ${REDIS_DATA_DIR_PATH}
sudo chown -R $REDIS_USER:$REDIS_USER ${REDIS_WORKING_DIR_PATH}

#PID
sudo touch ${REDIS_PID_FILE_FULL_PATH}
sudo chown -R $REDIS_USER:$REDIS_USER ${REDIS_PID_FILE_FULL_PATH}

# Out of Scope, but nice to know.
#Redis Service
#SYSTEMD_REDIS_SERVICE_FULL_PATH=/etc/systemd/system/redis_server.service
#sudo cp ${HOME}/systemd-redis_server.service ${SYSTEMD_REDIS_SERVICE_FULL_PATH}
#sudo sed -i "s/${REDIS_USER_PLACEHOLDER}/${REDIS_USER}/g" ${SYSTEMD_REDIS_SERVICE_FULL_PATH}
#sudo sed -i "s/${REDIS_USER_GROUP_PLACEHOLDER}/${REDIS_USER}/g" ${SYSTEMD_REDIS_SERVICE_FULL_PATH}
#sudo sed -i "s/${REDIS_WORKING_DIR_PATH_PLACEHOLDER}/${REDIS_WORKING_DIR_PATH}/g" ${SYSTEMD_REDIS_SERVICE_FULL_PATH}
#sudo sed -i "s/${REDIS_CONF_FILE_PLACEHOLDER}/${REDIS_CONF_FILE_FULL_PATH}/g" ${SYSTEMD_REDIS_SERVICE_FULL_PATH}
#sudo systemctl enable ${SYSTEMD_REDIS_SERVICE_FULL_PATH}
#sudo systemctl daemon-reload
#sudo systemctl start ${SYSTEMD_REDIS_SERVICE_FULL_PATH}
